#!/bin/bash

#SBATCH --job-name=d2q9-bgk
#SBATCH --time=01:10:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COMS033964
#SBATCH --output=d2q9-bgk.out
#SBATCH --exclusive 

#SBATCH --nodes=4
#SBATCH --ntasks-per-node=28
#SBATCH --cpus-per-task=1



echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

export OMP_PROC_BIND=close
export OMP_PLACES=cores
export OMP_NUM_THREADS=28



srun --mpi=pmi2 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun --mpi=pmi2 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# perf stat -e cycles,instructions,cache-references,cache-misses,branch-misses,\
# L1-dcache-loads,L1-dcache-load-misses,L1-dcache-stores,\
# L2_rqsts.all_demand_miss,L2_rqsts.references,\
# LLC-loads,LLC-load-misses,LLC-stores,\
# dTLB-loads,dTLB-load-misses,dTLB-stores \
# ./d2q9-bgk input_128x128.params obstacles_128x128.dat
