#!/bin/bash

#SBATCH --job-name=d2q9-bgk
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=28
#SBATCH --time=01:10:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COMS033964
#SBATCH --output=d2q9-bgk.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

export OMP_PROC_BIND=close
export OMP_PLACES=cores

for threads in {1..28}; do
    export OMP_NUM_THREADS=$threads
    echo "Running with $OMP_NUM_THREADS threads"
    
    ./d2q9-bgk input_128x128.params obstacles_128x128.dat
    ./d2q9-bgk input_128x256.params obstacles_128x256.dat
    ./d2q9-bgk input_256x256.params obstacles_256x256.dat
    ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

    echo "                                                "
    echo "================================================"
    echo "                                                "
done
´